version: '3'

services:
  db:
    image: bitnami/mongodb
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '80:80'
